### ISSUE TITLE
demo 容易造成误导, 且会闪退

### ISSUE THREAD

**Issue by TPQuietBro** [HuolalaTech/hll-wp-therouter-ios#2]
demo 运行起来后, 直接报错 not find route, 需要注释重定向代码才可行. 另外进入二级页面后返回闪退
Printing description of exception->exception:
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
(null)

问题代码:
- (void)dealloc
{
    !self.the_routerInfo.openCompleteHandler ?: self.the_routerInfo.openCompleteHandler(@"dealloc", @{@"key":self.title});
}
原因: self.title为nil

**Comment by crazy-zed** [comment]
Demo较为粗糙，有之前很多自定的测试内容，后续版本会更新demo，完善使用机制，感谢关注~
