### ISSUE TITLE
fetchRouterRegisterClass方法bundles遍历内部逻辑问题

### ISSUE THREAD

**Issue by ezeroyoung** [HuolalaTech/hll-wp-therouter-ios#22]
let bundles = CFBundleGetAllBundles() as? [CFBundle]
        for bundle in bundles ?? [] {
            let identifier = CFBundleGetIdentifier(bundle);
            
            if let id = identifier as? String {
                if excludeCocoapods {
                    if  id.hasPrefix(kSAppleSuffix) || id.hasPrefix(kSCocoaPodsSuffix) {
                        break
                    }
                } else {
                    if  id.hasPrefix(kSAppleSuffix) {
                        break
                    }
                }
            }
            
            let execURL = CFBundleCopyExecutableURL(bundle) as NSURL
            ...

两处`break`应该更改为`continue`，` let execURL = CFBundleCopyExecutableURL(bundle) as NSURL `转化` NSURL `应该可选。

**Comment by summerHearts** [comment]
1.1.4版本已发布
