### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by cyp6826256** [HuolalaTech/hll-wp-therouter-ios#3]
1、建议：拓展扫描组目录，不仅一个：scan脚本需支持指定目录（列表）扫描（支持本地pod仓库调试）（执行run script也有相应修改）
2、建议：支持scan去重功能（适配本地pod仓库与发版pod仓库重名ann问题）
3、建议：支持openvc自动赋值vc的属性值
4、建议：push枚举多支持从tabbar push
（稍后提个PR）

**Comment by summerHearts** [comment]
好的，提交后没问题的话会尽快出新版本

**Comment by summerHearts** [comment]
一直没反馈，暂时关闭这个话题
