### ISSUE TITLE
跳转一个没有注册的url，直接crash

### ISSUE THREAD

**Issue by DeqiuTseng** [HuolalaTech/hll-wp-therouter-ios#33]
以下是日志：
go =====>> url:sproject://com.feayear.proj/mine/info/interest/edit3
[]
[]
"routerMapPlist文件地址：/var/mobile/Containers/Data/Application/50298FC8-2CE6-4DB5-94C8-4F77755EB08D/Documents/routerMap.plist"
"routerMapJSON文件地址：/var/mobile/Containers/Data/Application/50298FC8-2CE6-4DB5-94C8-4F77755EB08D/Documents/routerMap.json"
"URL差集：[]"
"pagePathMap：[:]"
"classes差集：[]"
"sproject://com.feayear.proj/mine/info/interest/edit3"
TheRouterSwift/TheRouter.swift:132: Assertion failed: not matched, please check the router register is all readly
2024-01-23 16:24:51.787109+0800 WDZhiYin[98551:8468211] TheRouterSwift/TheRouter.swift:132: Assertion failed: not matched, please check the router register is all readly

然而看了文档设置了全局跳转失败函数也没有执行：
TheRouter.globalOpenFailedHandler { dic in
            print("跳转失败===>>>>")
        }

**Comment by summerHearts** [comment]
加群，腾讯会议视频快速解决下。
![IMG_5147](https://github.com/HuolalaTech/hll-wp-therouter-ios/assets/10678821/95d079f4-f557-4a77-8543-6205bb9ebda3) 到时候加我好友。名字：佐毅
