### ISSUE TITLE
iphone 6 ,iOS 12.5.7 上 getActivityViewController() 方法返回 nil

### ISSUE THREAD

**Issue by madaoCN** [HuolalaTech/hll-wp-therouter-ios#37]
![image](https://github.com/HuolalaTech/hll-wp-therouter-ios/assets/12007985/65dcb8b5-0be2-4444-a9f7-53808bd2f331) 

iphone 6 ,iOS 12.5.7 上 UIApplication.shared.windows 会获取到一个 hidden 的 window，这个 window 的 subview 为空，导致 getActivityViewController() 方法返回 nil

**Comment by summerHearts** [comment]
@madaoCN 我找了一个很破的手机，没能复现。详细信息如下:
![IMG_6968](https://github.com/HuolalaTech/hll-wp-therouter-ios/assets/10678821/857b5856-2fd6-4c8b-89da-bd82fdc7c232)

**Comment by summerHearts** [comment]
加你微信好友了，请提供下复现的Demo.否则无法帮助你解决问题，毕竟每个App的业务场景不一，视图层级结构也不一样
