### ISSUE TITLE
为啥demo下载podinstall后编译一堆crash

### ISSUE THREAD

**Issue by shijianmei** [HuolalaTech/hll-wp-therouter-ios#4]
podfile 是这样引入的：
use_modular_headers!

**Comment by summerHearts** [comment]
Podfile 中添加 use_modular_headers! 对所有的 pod 进行 Module 化。 crash信息是什么，我这边也加了use_modular_headers! 没有crash,方便的话，提供下demo,或者加下博客文章的交流群里直接联系。
