### ISSUE TITLE
基于Cocoapods做的Swift业务组件自动扫描支持这块能否加强

### ISSUE THREAD

**Issue by BlackMonkeyidea** [HuolalaTech/hll-wp-therouter-ios#54]
Swift业务组件中必须启用s.static_framework = true，否则实现了TheRouterable协议的Controller无法被自动扫描到，即使手动添加也会报错无法添加
```ruby
  # Router必须指定否则无法自动注册
  s.static_framework = true
```

断点调试发现fetchRouterRegisterClass中无法转换成TheRouterable从而导致无法加入到路由表中

想请教有什么解决方案，目前使用上不太优雅

**Comment by summerHearts** [comment]
@BlackMonkeyidea 等我测试下，应该很好解决

**Comment by BlackMonkeyidea** [comment]
已经收到你的邮件，我会尽快回复的

**Comment by summerHearts** [comment]
即使手动添加也会报错无法添加，具体是什么错呢

**Comment by summerHearts** [comment]
静态库在启动速度，包体积上都有优势，改成静态库是否什么成本嘛

**Comment by BlackMonkeyidea** [comment]
> 即使手动添加也会报错无法添加，具体是什么错呢

不好意思，上周开发环境有点异常，重新让同事测试了一遍，即使不开启静态库特性也可以正常扫描添加并跳转。

**Comment by BlackMonkeyidea** [comment]
> 静态库在启动速度，包体积上都有优势，改成静态库是否什么成本嘛

目前改成静态库的话，会与有些资源管理库（R.swift）冲突，需要适配比较麻烦，所以暂时没有启用静态库
