### ISSUE TITLE
tabbar跳转VC有具体示例吗？

### ISSUE THREAD

**Issue by Wuou** [HuolalaTech/hll-wp-therouter-ios#56]
1、tabbar跳转VC有具体示例吗？使用该框架如何配置？
2、TheRouter.customJumpAction的具体使用场景

**Comment by summerHearts** [comment]
具体是指从其他界面 跳转到tabbar 中的某一个嘛，如果是的话，稍后给出具体事例

**Comment by Wuou** [comment]
> 具体是指从其他界面 跳转到tabbar 中的某一个嘛，如果是的话，稍后给出具体事例

谢谢，是的
1、例如打开xx://tabbar?index=2 表示跳转到tabbar展示其vc
目前我市这么配置的，不知道是否合理：

static let tabbar:XZPath = "xz://tabbar"

// 跳转url示例：xz://tabbar?index=1
// 注册指定tabBar路由
addRouterItem(.tabbar, priority: 0) { params in
    guard let tabBarController = TheRouter.getKeyWindow().rootViewController as? UITabBarController else {
        return false
    }
    
    guard let index = Int(params["index"] as! String) else {
        return false
    }
    tabBarController.selectedIndex = Int(index)

    return true
}

2、UITabBarController中的vc是否也需要实现TheRouterable

3、似乎所有路由注册都需要实现TheRouterable协议，比较困惑，在我看来实现协议是为了更好的实现自动路由注册，为什么手动注册路由还需要实现该协议，每个vc都实现TheRouterable侵入性是否太大？

4、TheRouter.customJumpAction的使用场景还没get到点

**Comment by summerHearts** [comment]
@Wuou https://github.com/HuolalaTech/hll-wp-therouter-ios/tree/release/1.1.8 周末加班更新了一下，可以看下具体实现，先使用分支依赖看看效果，具体使用方式Demo中有，有不懂的直接微信我就行。
