### ISSUE TITLE
Xcode16下 Debug 模式下 objc_copyClassNamesForImage 的问题

### ISSUE THREAD

**Issue by madaoCN** [HuolalaTech/hll-wp-therouter-ios#59]
Xcode16 下 Debug 模式 `ENABLE_DEBUG_DYLIB` 选项默认开启，开启之后 `objc_copyClassNamesForImage` 主工程 image 调用失败，Debug 模式下会使用 `**.debug.dylib`文件，所以会有点问题。可以先将`ENABLE_DEBUG_DYLIB` 关闭，希望作者能顺便做下适配
![QQ_1725966507647](https://github.com/user-attachments/assets/ab8d5cf5-a025-4c2b-85aa-0ec33bf866da)

[官方文档：Enable Debug Dylib Support](https://developer.apple.com/documentation/xcode/build-settings-reference#Enable-Debug-Dylib-Support)
```
Setting name: ENABLE_DEBUG_DYLIB

If enabled, debug builds of app and app extension targets on supported platforms and SDKs will be built with the main binary code in a separate “NAME.debug.dylib”. A stub executor that loads the dylib will be the main binary. Enabling this setting is required for the previews execution engine and other modern development features to work. You can disable this setting if your target is not compatible.
```

**Comment by summerHearts** [comment]
![image](https://github.com/user-attachments/assets/698339a8-03b1-44d0-9f6d-dc27086e2c4c)
ENABLE_DEBUG_DYLIB 设置为NO
<img width="958" alt="image" src="https://github.com/user-attachments/assets/e39c66c4-eb32-4952-b2cc-a972519cfe50">
